Adiciona novos termos
OpenDevUFCG/glossario-ufcg pull request #107
Opened 2019-05-15 01:25 UTC by LukeHxH

Fixes #83 

**Descrição do bug/feature:**
Adiciona os novos termos propostos por @juliobguedes na #83.

Termos:
- SEI: Sistema Eletronico de Informações
- PRE: Pro Reitoria de Ensino
- AMARELINHA: Xerox Amarelinha
- Laguinho

OBS: O termo `CEEI` já existia.

**Solução adotada:**
Adicionei 2 termos no arquivo `locais.json`: AMARELINHA e Laguinho, assim como seus significados e aplicações em frase.
Adicionei 2 termos no arquivo `outros.json`: PRE e SEI, assim como seus significados e aplicações em frase.

2019-05-15 01:29 UTC, pedroespindula approved these changes

2019-05-15 04:09 UTC, juliobguedes requested changes
Creio que PRE fica melhor em Lugar, não? Acho interessante que um fera possa localizar o prédio da PRE aqui no laguinho... A descrição tá show, mas eu ainda acho q faz mais sentido estar em lugar e no texto adicionar ponto de referencia pro prédio. Que achas?

2019-05-15 09:50 UTC, LukeHxH commented
> Creio que PRE fica melhor em Lugar, não? Acho interessante que um fera possa localizar o prédio da PRE aqui no laguinho... A descrição tá show, mas eu ainda acho q faz mais sentido estar em lugar e no texto adicionar ponto de referencia pro prédio. Que achas?

Eu pensei muuuito a respeito de onde colocar a PRE, @juliobguedes. No fim das contas, acabei pensando em colocar em "outros" porque a PRE não é um "bloco" propriamente dito, é um órgão da UFCG, e até a descrição eu coloquei como um órgão e deixei a informação a respeito da localização do bloco em uma das aplicações em frase. Mas eu também não tenho certeza, e se acharem melhor colocar em lugar, eu posso fazer a mudança. :smile:

2019-05-15 13:19 UTC, pedroespindula commented
> > Creio que PRE fica melhor em Lugar, não? Acho interessante que um fera possa localizar o prédio da PRE aqui no laguinho... A descrição tá show, mas eu ainda acho q faz mais sentido estar em lugar e no texto adicionar ponto de referencia pro prédio. Que achas?
> 
> Eu pensei muuuito a respeito de onde colocar a PRE, @juliobguedes. No fim das contas, acabei pensando em colocar em "outros" porque a PRE não é um "bloco" propriamente dito, é um órgão da UFCG, e até a descrição eu coloquei como um órgão e deixei a informação a respeito da localização do bloco em uma das aplicações em frase. Mas eu também não tenho certeza, e se acharem melhor colocar em lugar, eu posso fazer a mudança.

Eu também acho melhor em outros @juliobguedes, pq como @LukeHxH disse, a PRE não é só um lugar.

2019-05-15 13:19 UTC, pedroespindula approved these changes

2019-05-23 01:23 UTC, thayannevls approved these changes

2019-06-11 00:25 UTC, merged