Adicionado .prettierrc e consertada formatação dos arquivos
OpenDevUFCG/glossario-ufcg pull request #125
Opened 2019-10-04 23:15 UTC by estacioneto

**Descrição do bug/feature:**

Adicionado arquivo `.prettierrc` e consertada formatação de arquivos `.js`

**Solução adotada:**

Após adição do arquivo, foi rodado o comando `prettier` (instalado globalmente em minha máquina pois ainda não sei se é necessário adicionar ao projeto).

2019-10-05 00:16 UTC, thayannevls commented
Oi @estacioneto! Obrigada pela contribuição, ficou ótimo já.

Na verdade queremos sim o prettier no projeto, então pode adicionar nas dependências 😄

2019-10-05 07:11 UTC, fanny submitted a review, later dismissed

2019-10-05 23:05 UTC, thayannevls submitted a review, later dismissed
Obrigada pela contribuição Estácio! ❤️ 

Resolve os conflitos que eu dou merge 😄

2019-10-07 19:09 UTC, fanny requested changes

2019-10-07 19:09 UTC, fanny commented on src/components/glossary/GlossaryPage.js.orig
> +<<<<<<< HEAD
js.orig? :thinking: 
Pode apagar?

2019-10-07 19:09 UTC, fanny commented on src/components/glossary/results/SearchResults.js.orig
> +import React from 'react';
aqui tb

2019-10-07 19:09 UTC, fanny commented on src/components/glossary/results/SearchResults_BACKUP_72242.js
> +<<<<<<< HEAD
BACKUP? :thinking:

2019-10-07 19:09 UTC, fanny commented on src/components/glossary/results/SearchResults_BASE_72242.js
> +import React, {Component} from "react";
BASE?

2019-10-07 19:09 UTC, fanny commented on src/components/glossary/results/SearchResults_LOCAL_72242.js
> +import React from 'react';
LOCAL?

2019-10-07 19:09 UTC, fanny commented on src/components/glossary/results/SearchResults_REMOTE_72242.js
> +import React, { Component } from 'react';
REMOTE?

2019-10-07 20:04 UTC, estacioneto commented
Valeu, @fanny! Não tinha visto... Sorry :/

2019-10-07 21:03 UTC, thayannevls approved these changes

2019-10-07 22:33 UTC, fanny approved these changes

2019-10-07 22:33 UTC, merged