add Header component w/ react-router-prop-types
OpenDevUFCG/glossario-ufcg pull request #128
Opened 2019-10-06 21:57 UTC by luizcieslak

Fixes #119 

**Descrição do bug/feature:**
Criação do componente `<Header />`

**Solução adotada:**
* Separação lógica e dos estilos do componente
* O componente header recebe as `props` do parent para ter acesso as funções do `react-router`
* Verificação das props através do pacote `react-router-prop-types`

**TODO:**
A separação desse componente não remove a atribuição de estilo condicional no `GlossaryPage`, conforme descrição da issue:

https://github.com/OpenDevUFCG/glossario-ufcg/blob/3f468202b017983dc5bf593719ef4ca9911cc335/src/components/glossary/GlossaryPage.js#L41

Porém, no meu entendimento, essa condicional diz como o `Header` deve se comportar na tela de acordo com o `term` passado.

Para essa condicional sumir, deve-se criar páginas separadas, uma para a "Homepage" e outra que mostra o `TermCard`, assim cada página posiciona o `Header` do jeito que for preciso. 

Fico aberto para discussões caso pensem o contrário, ou o que disse acima deve estar nesse PR também 🤗

2019-10-07 14:19 UTC, pedroespindula submitted a review, later dismissed
Ola, @luizcieslak, muito obrigado pela contribuição! O refactor ficou muito bom e pra mim, sem nenhum problema. Aprovadissimo! Só vou esperar @fanny para poder dar merge já que ela se colocou como revisora.

2019-10-07 19:17 UTC, fanny requested changes

2019-10-07 19:17 UTC, fanny commented on src/components/common/Header/Header.js
> +export default function Header(props) {
Pode colocar numa const e exportar depois? Só pra ser coerente com as outras definicoes. Algo como 
```suggestion
const Header = (props) => {}
export default Header
```

2019-10-07 19:17 UTC, fanny commented on src/components/common/Header/Header.js
> +	return (
Ajusta a identação daqui, por favor :heart:

2019-10-07 19:17 UTC, fanny commented on src/components/glossary/GlossaryPage.js
> +      <Header {...props} isSearchEmpty={isSearchEmpty} />
:notbad:

2019-10-08 20:20 UTC, luizcieslak commented on src/components/common/Header/Header.js
> +export default function Header(props) {
Ops, foi

2019-10-09 12:27 UTC, fanny approved these changes

2019-10-09 12:27 UTC, merged