Normalizando o código com as regras predefinidas do eslint. Adicionando (verificação eslint) dentro da pipeline do travis.
OpenDevUFCG/glossario-ufcg pull request #133
Opened 2019-10-10 20:03 UTC by jonathan-sh

Fixes #132 

**Descrição do bug/feature:**
Extinguir falhas do lint.
Deseja-se usar a verificação do lint no travisCI, e, para não quebrar a pipeline, essas falhas devem ser corrigidas.

**Solução adotada:**
1-) Normalizando o código com as regras predefinidas do eslint.
     ✓ removendo variáveis declaras e não utilizadas. 
     ✓ removendo logs do console. 
     ✓ adicionando algumas PropTypes
     ✓ adicionando (verificação do eslint) nas configurações de pre-commit.

2-)Adicionando (verificação eslint) dentro da pipeline do travis. 
     ✓ [travis-log](https://travis-ci.org/jonathan-sh/glossario-ufcg/jobs/596270551#L208)

**TODO:**
   Como eu usei a minha conta para testar a pipeline do travis, não havia a variável de ambiente `$github_token`. Temos que verificar em uma conta aonde haja essa variável. 
   Acho que seria interessante adicionar um `shield` com o resultado do build lá no `README`

2019-10-11 17:05 UTC, pedroespindula requested changes
Oi, @jonathan-sh, muito obrigado pela sua contribuição! Fiz alguns comentários quanto a alguns logs que foram removidos, ao usar o npm ao inves do yarn pra executar o lint pre-commit e uma propType que deveria ter outro nome. Fora isso, tudo certinho!

2019-10-11 17:05 UTC, pedroespindula commented on src/scripts/orderData.js
> -console.log('\033[1;93m Reordenando arquivos de dados... \033[0m');
Esse log não deve ser removido. Pra poder passar no lint tu pode desabilitar a regra que ele ta quebrando e habilitar depois da linha.

2019-10-11 17:05 UTC, pedroespindula commented on package.json
> +      "pre-commit": "npm run lint && node src/scripts/orderData.js && git add src/lib"
Usar yarn ao inves de npm

```suggestion
      "pre-commit": "yarn run lint && node src/scripts/orderData.js && git add src/lib"
```

2019-10-11 17:05 UTC, pedroespindula commented on .travis.yml
> +  - yarn run lint
Aqui está bom, mas se tu puder e souber, cria uma pipeline só pra o lint e outra só pra o build. Se não der pra criar, avisa que eu aceito mesmo assim :smile:.

2019-10-11 17:05 UTC, pedroespindula commented on src/scripts/orderData.js
> -console.log('\033[1;93m Pronto! :) \033[0m');
Esse log também não deve ser removido.

2019-10-11 17:05 UTC, pedroespindula commented on src/components/common/Icon/Icon.js
> +const Icon = ({ icon, color, size }) => (
No caso desse componente, o nome da prop utilizada para dar cor ao icone deveria ser `iconColor`. Ai ao inves de tu mudar o nome da prop aqui pra `color` pra ele usar o propTypes que foi definido em baixo, tu muda o nome na definição do propTypes. 

```suggestion
const Icon = ({ icon, iconColor, size }) => (
```

2019-10-11 17:05 UTC, pedroespindula commented on src/components/common/Icon/Icon.js
> +  <i className="material-icons" style={{ color: color, fontSize: size }}>
```suggestion
  <i className="material-icons" style={{ color: iconColor, fontSize: size }}>
```

2019-10-11 18:21 UTC, jonathan-sh commented on src/scripts/orderData.js
> -console.log('\033[1;93m Reordenando arquivos de dados... \033[0m');
Eu levei em consideração isso, porém não queria mexer nas configurações que vocês haviam deixado no projeto, posso mudar isso sem problemas.

2019-10-11 18:21 UTC, jonathan-sh commented on package.json
> +      "pre-commit": "npm run lint && node src/scripts/orderData.js && git add src/lib"
Isso é culpa no meu vicio de npm, my bad.
Troco sim :smile:

2019-10-11 18:21 UTC, jonathan-sh commented on .travis.yml
> +  - yarn run lint
Vou montar uma para sugestão.

2019-10-11 18:22 UTC, jonathan-sh commented on src/scripts/orderData.js
> -console.log('\033[1;93m Pronto! :) \033[0m');
Deixando esse tipo de log no projeto, além de ter de mudar a configuração de [no-console](https://eslint.org/docs/rules/no-console#disallow-the-use-of-console-no-console) do eslint, também teremos de decidir se alteramos a opção [no-octal](https://eslint.org/docs/rules/no-octal) ou adicionamos uma lib como essa [color-lib](https://www.npmjs.com/package/colors) para logs coloridos.

2019-10-11 18:22 UTC, jonathan-sh commented on src/components/common/Icon/Icon.js
> +const Icon = ({ icon, color, size }) => (
Não quiz mudar propTypes já definidas, mas como esse é caso, mudo sim.

2019-10-13 13:19 UTC, fanny commented on src/scripts/orderData.js
> -console.log('\033[1;93m Pronto! :) \033[0m');
Oie @jonathan-sh! Muito orbigada pela contribuição! Acho que adicionar uma lib pra uma coisa tão simples como essa, é `overkill`, pelo que to vendo, a regra `no-octal` é ok, quando se trata de strings, pq se for isso, acho que n tem problema do jeito que tá. Sobre a regra do console, eu acho que n seria legal remover, talvez ignorar só pra esse arquivo. O que achas?

2019-10-14 14:28 UTC, jonathan-sh commented on src/scripts/orderData.js
> -console.log('\033[1;93m Pronto! :) \033[0m');
Eai @fanny,  salve! 
Que isso, tô me divertindo com esse negócio de opensource :smile:.
Então, tbm acho `over kill` adicionar uma lib soimente para esse caso, das ideas propostas, acredito que adicionar o arquivo no `.eslintignore` seja a de `menor` impacto.
Como vocês @fanny  @pedroespindula  acham que eu devo proceder....
Gero um outro pullrequest, somente com a alteração do `.eslintignore` +  `voltando os logs` 
**ou** vcs conhecem outra forma de fazer alteração em um arquivo que não faz parte deste pullrequest?

2019-10-15 18:41 UTC, fanny commented on src/scripts/orderData.js
> -console.log('\033[1;93m Pronto! :) \033[0m');
@jonathan-sh não sei se entendi muito bem, desculpa!! Qual seria o problema de tu adicionar o `.eslintignore` e adicionar os logs de novo? :thinking:

2019-10-15 19:13 UTC, jonathan-sh commented on src/scripts/orderData.js
> -console.log('\033[1;93m Pronto! :) \033[0m');
Vishi @fanny, acho que eu não fui claro...
Já decidimos que iremos adicionar o `.eslintignore` e voltar com os logs.
A minha duvida é de *como* iremos fazer isso. 
Devo fazer isso em outro PR a parte **ou** vocês conhecem outra forma de adicionar um arquivo desse commit?

2019-10-16 17:47 UTC, fanny commented on src/scripts/orderData.js
> -console.log('\033[1;93m Pronto! :) \033[0m');
Eu achei que era só dá o `git add <nome_arquivo>` && `git commit -m '..'` && `git push`
Realmente não tô conseguindo enxergar o problema, mas se você se sente confortável abrindo outra PR, faz isso!! Só referencia nela, essa daqui, pra eu lembrar de merjar as 2.

2019-10-17 19:38 UTC, fanny submitted a review, later dismissed

2019-10-22 13:00 UTC, jonathan-sh commented on src/scripts/orderData.js
> -console.log('\033[1;93m Pronto! :) \033[0m');
@fanny eu realmente não sabia que era tão simples, pensei que teria de fazer outro pullrequest, mas como você explicou, um push convencional resolveu. :smiley:  
No histórico dos commit fica mais claro de entender: [commits do pr] (https://github.com/OpenDevUFCG/glossario-ufcg/pull/133/commits). 
Muito obrigado pela atenção.

2019-10-24 01:26 UTC, fanny approved these changes

2019-10-24 01:28 UTC, fanny commented on src/scripts/orderData.js
> -console.log('\033[1;93m Pronto! :) \033[0m');
Isso, valeu e desculpa pela confusāo hehehe! Se1 precisar de ajuda com qualquer coisa, estou à disposiçāo.

2019-10-24 10:48 UTC, fanny commented
@pedroespindula pode merjar?

2019-10-24 10:51 UTC, pedroespindula commented
> @pedroespindula pode merjar?

Vou revisar agora, pera

2019-10-24 10:52 UTC, pedroespindula approved these changes

2019-10-24 10:52 UTC, pedroespindula commented
Agora pode @fanny

2019-10-24 10:54 UTC, pedroespindula commented
Muito obrigado @jonathan-sh pela sua contribuição! Tu não tem noção do quanto a gente fica feliz em receber uma contribuição como essa tua, de verdade. Fique a vontade pra contribuir mais e qualquer dúvida é só falar, seja por um email ou pelo nosso discord.

2019-10-24 17:21 UTC, juliobguedes commented
@fanny @pedroespindula resolvi a thread que ainda estava aberta. Alguma perspectiva da pipeline ser corrigida pra podermos merjar o código?

2019-10-24 17:49 UTC, merged