Adição da disciplina optativa geral infosoc
OpenDevUFCG/glossario-ufcg pull request #141
Opened 2019-10-19 21:01 UTC by FelipeAmorimFerreira

Fixes #70 

**Descrição do bug/feature:**
Falta de disciplinas optativas no disciplinas.json.

**Solução adotada:**
Disciplina Informática e Sociedade adicionada ao json.

**TODO:**
Adicionar mais disciplinas optativas.

2019-10-20 10:20 UTC, fanny commented
Obrigada pela contribuicāo! @FelipeAmorimFerreira

2019-10-20 10:23 UTC, fanny requested changes

2019-10-20 10:23 UTC, fanny commented on src/lib/locais.json
> +            "meaning": "[Laboratório de Ciência da Computação 2](https://www.google.com.br/maps/@-7.2136349,-35.907708,19.5z) é o laboratório liberado para o uso dos alunos do curso de Ciência da Com
Pode manter o significado como antes? Pra adicionar a localizaçāo cria um kovo campo, como [aqui](https://github.com/OpenDevUFCG/glossario-ufcg/blob/305cc910ea8268d11e6b724ec4e8a65967d4daad/src/lib/locais.json)

2019-10-20 16:14 UTC, FelipeAmorimFerreira commented on src/lib/locais.json
> +            "meaning": "[Laboratório de Ciência da Computação 2](https://www.google.com.br/maps/@-7.2136349,-35.907708,19.5z) é o laboratório liberado para o uso dos alunos do curso de Ciência da Com
Sim, vou deixar está no exemplo.

2019-10-20 19:34 UTC, FelipeAmorimFerreira commented
Novo commit feito

2019-10-24 02:26 UTC, thayannevls approved these changes
Obrigada pela contribuição! ❤️

2019-10-24 10:50 UTC, fanny approved these changes

2019-10-24 10:50 UTC, merged