Adicionei "Humanas"
OpenDevUFCG/glossario-ufcg pull request #146
Opened 2019-10-19 21:24 UTC by caetanobca

Fixes #ISSUE_NUMBER

**Descrição do bug/feature:**

**Solução adotada:**

**TODO:**

2019-10-20 10:14 UTC, fanny commented
Muito obrigada pela contribuiçāo! @caetanobca

2019-10-20 10:14 UTC, fanny submitted a review, later dismissed

2019-10-21 18:06 UTC, pedroespindula requested changes

2019-10-21 18:06 UTC, pedroespindula commented on src/lib/locais.json
>      ]
Falta uma virgula aqui.
```suggestion
    ],
```

2019-10-24 18:05 UTC, juliobguedes requested changes
Oi @CaetanoAlbuquerque, obrigado pela PR! Se possível, adiciona a mudança solicitada por @pedroespindula. A vírgula é necessária para o arquivo ser um JSON válido, isto é, sem ela o arquivo "não compila".

2019-10-24 18:19 UTC, juliobguedes approved these changes
Massa, valeu pela alteração! :)

2022-10-28 21:36 UTC, closed without merging