Adicionado Mapa no Cartão do Termo. #93
OpenDevUFCG/glossario-ufcg pull request #149
Opened 2019-10-20 03:04 UTC by davig-sousa

Fixes #93 

**Descrição do bug/feature:**
É adicionada uma div com a localização, ou seja, um mapa interativo propriamente dito, do termo do tipo "locais".

**Solução adotada:**
Para esse box aparecer, basta que o termo tenha a propriedade "localization" setada com um array de dois valores, [latitude, longitude].
Exemplo para o LCC1:
```
"LCC1": [
        {
            "acronym": "LCC1",
            "meaning": "Laboratório de Ciência da Computação 1 é o laboratório mais antigo do curso de Ciência da Computação da UFCG e atualmente é usado principalmente para aulas em algumas disciplinas. Localiza-se no térreo do [REENGE](https://goo.gl/maps/RM26SXMW5tT2) (bloco CB).",
            "type": "Sala",
            "entry": "Laboratório de Ciência da Computação 1",
            "examples": [
                "O miniteste de amanhã será no LCC1!",
                "Pessoal, amanhã a nossa aula será no LCC1."
            ],
            "localization": [
                -7.21383,
                -35.90899
            ]
        }
    ]```

O mapa foi adicionado graças a existência do Projeto (OpenStreetMap)[https://www.openstreetmap.org/search?whereami=1&query=-7.21502%2C-35.90853#map=17/-7.21503/-35.90853] e do (OpenLayers)[https://openlayers.org/].

Se o array não existir, uma div vazia é adicionada ao TermCard, portanto, não produz efeito visual algum.

**TODO:**
- Precisamos adicionar o "localization" para as demais localidades presentes em locais.json.
- Precisa-se adicionar essa necessidade à Documentação do projeto.
- Talvez, aprimorar a responsividade do mapa em dispositivos móveis.

2019-10-20 10:09 UTC, fanny commented
Muito obrigada pela contribuiçāo @davig-sousa! Em breve recisaremos!

2019-10-21 17:49 UTC, pedroespindula requested changes
Oi, @davig-sousa, muito obrigado pela contribuição!!!! Ficamos muito felizes ao receber esse PR e por ver que tu fez isso de forma simples e eficiente. Só existem três coisas que eu vou pedir pra tu mudar. A primeira é usar outra unidade sem ser `px` (está comentado onde deve ser modificado). A outra é mover o componente `LocalizationIfExists` para um arquivo a parte na pasta `common`. E a ultima é, se possivel, fazer com que o mapa preencha o card na horizontal. Se não conseguir fazer essa ultima, só avisar que eu aprovo e depois isso é feito. Muito obrigado novamente, ajudasse e muito a gente com esse PR.

2019-10-21 17:49 UTC, pedroespindula commented on src/components/common/TermCard/TermCard.css
> +  height: 200px;
Tem como usar outra unidade sem ser `px`? Só pra tentar deixar mais responsivo.

2019-10-21 17:49 UTC, pedroespindula commented on src/components/common/TermCard/TermCard.js
> +const LocalizationIfExists = ({ entry, localization }) => {
Se tu puder, cria esse componente num arquivo separado, de preferencia nos componentes `common` da aplicação., ai tu so importa ele aqui.

2019-10-21 18:56 UTC, davig-sousa commented on src/components/common/TermCard/TermCard.css
> +  height: 200px;
Certo!

2019-10-21 18:56 UTC, davigps commented on src/components/common/TermCard/TermCard.js
> +const LocalizationIfExists = ({ entry, localization }) => {
Ok!

2019-10-21 20:13 UTC, davig-sousa commented
As três mudanças foram realizadas! Qualquer inconsistência, só avisar que irei repará-la!
E eu que agradeço a iniciativa e ao projeto de vocês, tem me ajudado muito a aprender mais sobre o open source e as tecnologias de desenvolvimento web! Já me sinto parte do OpenDevUFCG!

2019-10-24 02:16 UTC, thayannevls requested changes

2019-10-24 02:16 UTC, thayannevls commented on src/lib/locais.json
> +            "localization": [
Era melhor ser um objeto, não?

2019-10-24 02:17 UTC, thayannevls commented
Muito obrigada pela contribuição!! Fiz uma pergunta que talvez seja uma melhoria, se não concordar, só comentar!

2019-10-24 10:26 UTC, pedroespindula commented on src/lib/locais.json
> +            "localization": [
Pensando bem agora, eu acredito que ficaria melhor tbm mas como seria esse objeto? :thinking:

2019-10-24 10:32 UTC, pedroespindula submitted a review, later dismissed
Por mim está aprovado demais!!! Ficou realmente muito bom! Muito obrigado @davig-sousa :smile:

2019-10-24 10:45 UTC, fanny commented on src/lib/locais.json
> +            "localization": [
concordo com @thayannevls, acho que seria algo como:
```js
    location: {
      latitude: '-7.21333',
      longitude: '-35.90732'
    }
```
@pedroespindula

2019-10-24 10:45 UTC, fanny commented on src/components/common/LocalizationIfExists/LocalizationIfExists.js
> +      return (<div/>);
```suggestion
      return <></>;
```
Adicionando essa tag assim, chamada de `Fragment` no React, nenhuma tag é adicionada na arvore de componentes HTML(DOM), que acredito fazer mais sentido nessa condição.

2019-10-24 10:45 UTC, fanny commented on src/components/common/LocalizationIfExists/LocalizationIfExists.js
> +      let iconStyle = new Style({
```suggestion
      const iconStyle = new Style({
```

2019-10-24 10:46 UTC, fanny commented
Parabéns pelo trabalho @davig-sousa! Ficou incrível!

2019-10-24 10:48 UTC, pedroespindula commented on src/lib/locais.json
> +            "localization": [
Acho que assim fica ótimo, @fanny

2019-10-24 10:49 UTC, pedroespindula commented on src/components/common/LocalizationIfExists/LocalizationIfExists.js
> +      return (<div/>);
Aprendendo com @fanny todos os dias, sabia disso nunca kkkkkkkk

2019-10-24 18:05 UTC, davig-sousa commented on src/lib/locais.json
> +            "localization": [
@thayannevls @fanny @pedroespindula 
Poderia ser mesmo! Eu acho um array menos verboso, porque não é necessário escrever os atributos, entretanto, um objeto fica mais organizado e define onde é latitude e longitude, irei commitar com essa mudança, porém ao invés de serem strings, manterei o tipo Number, para facilitar a escrita e o fato do OpenLayers utilizar o dado no tipo Number mesmo.

2019-10-24 18:34 UTC, davig-sousa commented
Irei fazer os commits restantes.

2019-10-24 19:29 UTC, thayannevls commented on src/lib/locais.json
> +            "localization": [
@davig-sousa tu se importa de botar **latitude** e **longitude** em inglês?

2019-10-24 20:02 UTC, davig-sousa commented on src/lib/locais.json
> +            "localization": [
Não me importo não, mas eu conheço em inglês como latitude e longitude mesmo, tem alguma outra sugestão? Ou eu não compreendi a pergunta.

2019-10-25 00:30 UTC, davig-sousa commented
@fanny  @pedroespindula @thayannevls 
Fiz as alterações pedidas, adicionei o objeto location no JSON e adicionalmente troquei o nome da implementação de localization para location.
Exemplo de local:
```javascript
    "CAA": [
        {
            "meaning": "CAA é um dos principais blocos de aula do setor de exatas. O CAA fica localizado em frente à biblioteca e normalmente você encontra pessoas de diferentes cursos no CAA.",
            "type": "Bloco",
            "entry": "CAA",
            "examples": [
                "As aulas de Probabilidade esse semestre são no CAA 408.",
                "Te encontro perto dos elevadores do CAA."
            ],
            "location": {
                "latitude": -7.2142,
                "longitude": -35.90824
            }
        }
    ],
```

2019-10-28 11:43 UTC, thayannevls submitted a review, later dismissed
Muito obrigada pela contribuição!! ❤

2019-10-28 11:52 UTC, fanny submitted a review, later dismissed

2019-10-28 13:27 UTC, thayannevls approved these changes

2019-10-28 13:27 UTC, merged