Adiciona os termos "tg, pijama, leite e bola"
OpenDevUFCG/glossario-ufcg pull request #23
Opened 2019-02-17 14:21 UTC by FannyVieira

2019-02-17 17:18 UTC, JoseRenan requested changes
Oi, @FannyVieira obg pelo PR :heart: modifiquei os tipos que tu colocou como Termo para Gíria, mas gostaria de pedir uma coisinha kkkkkkk no recém merjado PR #22 a gente ordenou os dados em ordem alfabética, daí gostaria de pedir pra atualizar e colocar na ordem os que tu adicionou kkkkk se não for pedir demais :cry: :heart:  vou colocar essas informações no README ou CONTRIBUTING em breve :heart:

2019-02-18 08:39 UTC, FannyVieira commented
Okay, irei modificar

2019-02-18 10:44 UTC, FannyVieira commented
Eu tava pensando agora que a chave do dicionário é o acrônimo, ainda é necessário esse atributo `acronym`? porque por exemplo se eu tiver `P1` que tem vários significados eu teria que fazer isso, pelo que entendi:
`    "P1": [
        {
            "acronym": "P1",
            "meaning": "Programação 1",
            "type": "Disciplina"
        },
        {
            "acronym": "P1",
            "meaning": "Projeto de computação 1",
            "type": "Disciplina"
        }
    ],
`
Mas pela chave já da pra saber

2019-02-27 02:52 UTC, JoseRenan approved these changes
Topppp, mto obg :heart:

2019-02-27 02:55 UTC, JoseRenan commented
> Eu tava pensando, agora que a chave do dicionário é o acrônimo, ainda é necessário esse atributo `acronym`? porque por exemplo se eu tiver `P1` que tem vários significados eu teria que fazer isso, pelo que entendi

Eu tava falando sobre isso essa semana com @paulojbleitao porque a gente tá com um problema da busca por URL ser case insensitive, só que algumas siglas ficam estranhas se forem tudo maiusculo como JoDi, se for JODI alguém vai achar que cada letra representa uma palavra... daí a chave seria como o nome seria buscável e o acronym seria como ele seria exibido na interface :thinking: criarei uma issue pra isso, ou pode ser discutido nesse pr tbm #26

2019-02-27 02:56 UTC, merged