Incrementa conteúdo de algumas disciplinas
OpenDevUFCG/glossario-ufcg pull request #53
Opened 2019-03-07 16:48 UTC by marianabianca

disciplinas alteradas: AA, LP2, OAC, P1

Dados atualizados como é explicado na issue #44

2019-03-07 17:50 UTC, JoseRenan requested changes
Oi @marianabianca, bem vinda!!!! Muito obrigado pelo PR ❤️  Solicitei algumas alterações apenas pra gente padronizar com os outros que já temos!

2019-03-07 17:50 UTC, JoseRenan commented on src/lib/disciplinas.json
> +            "meaning": "Algoritmos Avançados é um disciplina optativa específica que foca no estudo de algoritmos para uso em olimpíadas de programção.",
Seria bom especificar que essa é uma disciplina de ciência da computação na UFCG, pois estamos abertos a receber siglas de outros cursos também

2019-03-07 17:50 UTC, JoseRenan commented on src/lib/disciplinas.json
> +            "meaning": "Algoritmos Avançados é um disciplina optativa específica que foca no estudo de algoritmos para uso em olimpíadas de programção.",
Isso se aplica às outras disciplinas adicionadas tambem 😄

2019-03-07 17:50 UTC, JoseRenan commented on src/lib/disciplinas.json
> +            "meaning": "Laboratório de Programação 2 é a disciplina obrigatória do 2º em que colocamos em prática o que aprendemos em Programação 2, cujo foco está em programação orientada ao objeto.
Nesse caso não seria melhor "na qual colocamos..."? (serve pras outras também)

2019-03-07 17:50 UTC, JoseRenan commented on src/lib/disciplinas.json
> +            "meaning": "Organização e Arquitetura de Computadores é uma discilina obrigatória do 4º em que aprendemos como é a arquitetura de um computador internamente e como funcionam seus componen
Seria bom indicar que o 4o que tu fala é o 4o período (serve pras outras também)

2019-03-08 21:00 UTC, danielmitre commented
oi, terminei primeiro

2019-03-13 04:14 UTC, JoseRenan approved these changes
@marianabianca, ficou MUITO BOMM!!! mto obg mesmo :heart: Temos oficialmente uma "Google Local Guide" no Glossário KKKKKKKKKKKK

2019-03-13 04:14 UTC, merged