Nova interface
OpenDevUFCG/glossario-ufcg pull request #71
Opened 2019-03-12 12:16 UTC by pedroespindula

Fixes #20

**Descrição do bug/feature:** Muda a interface pra um design mais amigavel e intuitivo.

**Solução adotada:**
- Antes:
1. Sem termo selecionado:
![Screenshot from 2019-03-12 09-13-37](https://user-images.githubusercontent.com/38431219/54199236-2f948300-44a7-11e9-8c9e-90a5ce97a36d.png)

2. Com termo selecionado:
![Screenshot from 2019-03-12 09-14-28](https://user-images.githubusercontent.com/38431219/54199278-46d37080-44a7-11e9-81ef-9833aeeb782c.png)

- Depois:
1. Sem termo selecionado:
![image](https://user-images.githubusercontent.com/38431219/54199180-0b38a680-44a7-11e9-98cf-54cb40eeb5e9.png)

2. Com termo selecionado:
![image](https://user-images.githubusercontent.com/38431219/54199203-18559580-44a7-11e9-8c1c-55cdb9dbeb47.png)

**TODO:** n/a

2019-03-12 12:28 UTC, thayannevls commented
Seria bom na tela que existe um termo selecionado, ao clicar na logo que fica em cima, ele volta pra tela inicial sem nenhum termo selecionado. Creio que seja fácil fazer isso agora

![Desenho sem título](https://user-images.githubusercontent.com/6867958/54200073-345a3680-44a9-11e9-8567-211c4f5cfecf.png)

2019-03-12 12:32 UTC, thayannevls commented
O botão de pesquisa não funciona, só dá pra pequisar com o enter. Pelo que entendi é porque só acha o termo a partir da sugestão do componente de input e seria complicado pra vocês implementarem isso agora?

Se for ruim de ajeitar pra pesquisar com o botão quando existe o termo, talvez tirar esse botão

2019-03-12 12:38 UTC, thayannevls requested changes
Adicionar opção de clique na logo na tela com o termo selecionado, os outros problemas vocês podem abrir issue pra fazer depois ou fazer agora.

2019-03-12 12:39 UTC, thayannevls commented
A responsividade em celulares pequenos, como a do Iphone, ficou boa mas falta uns retoques. Eu acho agoniante quando fica com a barra horizontal porque dificulta o uso. 

Aconselho criar uma issue pra isso e não fazer agora.

2019-03-13 00:01 UTC, thayannevls approved these changes

2019-03-13 00:26 UTC, JuanBarros2 approved these changes

2019-03-13 00:27 UTC, merged