Adicionando o termo 'Prob' ao arquivo de disciplinas
OpenDevUFCG/glossario-ufcg pull request #78
Opened 2019-03-13 23:19 UTC by davidedup

**Descrição do bug/feature:**
Adicionando o termo 'Prob'.

**Solução adotada:**
Criar mais um objeto no arquivo Json.

2019-03-13 23:51 UTC, JoseRenan requested changes
Bem vindo, @davidedup :heart: eu pedi umas alterações só pra complementar o conteúdo

2019-03-13 23:51 UTC, JoseRenan commented on src/lib/outros.json
> +            "meaning": "Programa de Educação Tutorial é um programa do Governo Federal brasileiro de estímulo a atividades de pesquisa, ensino e extensão universitárias, no nível de graduação.",
Podia falar tbm que PETs conhecidos na UFCG são os de matemática e computação, e falar de exemplos de atividades que o pet no geral faz

2019-03-17 13:20 UTC, juliobguedes commented on src/lib/outros.json
> +            "meaning": "Programa de Educação Tutorial é um programa do Governo Federal brasileiro de estímulo a atividades de pesquisa, ensino e extensão universitárias, no nível de graduação.",
Acho que exemplificar quais PETs são conhecidos pode parecer depreciar os não mencionados :/ Os PETs Elétrica e ADM fazem muita coisa também, então mudando o request pra adicionar só os exemplos de atividade q o PET faz.

2019-03-17 18:35 UTC, JoseRenan approved these changes
Mto bommmm @davidedup valeu :heart: e volte sempre ;) KKKKK

2019-03-17 18:36 UTC, merged