Adicionando configuração de produção do webpack
OpenDevUFCG/glossario-ufcg pull request #86
Opened 2019-03-19 12:29 UTC by juliobguedes

Closes #14 

**Descrição do bug/feature:**
Adicionar configuração de produção do webpack

**Solução adotada:**
Separei o arquivo de config do webpack em três arquivos:
* O common, com configurações em comum entre desenvolvimento e produção;
* O dev, com configurações específicas para desenvolvimento;
* O prod, com configurações específicas para produção

Além disso, reorganizei os arquivos numa pasta chamada `webpack`, para deixar mais coerente, e corrigi os scripts no `package.json`

**TODO:**
N/A

2019-03-19 22:09 UTC, pedroespindula submitted a review, later dismissed

2019-03-20 02:29 UTC, JoseRenan requested changes

2019-03-20 02:29 UTC, JoseRenan commented on webpack/webpack.common.js
> +    entry: ['react-dev-utils/webpackHotDevClient', `${parentDir}/src/index.js`],
Será se não tem um jeito de deixar esse `'react-dev-utils/webpackHotDevClient'` só no develop? digo, talvez tenha de criar um entry em cada arquivo, acho que é uma solução ok

2019-03-21 03:06 UTC, JoseRenan approved these changes
Topp mermão!

2019-03-21 04:08 UTC, merged