Adição de exemplos para jogos e TCC, e algumas alterações
OpenDevUFCG/glossario-ufcg pull request #97
Opened 2019-04-06 01:18 UTC by RaylaMedeiros

#44 

**Descrição do bug/feature:**
Foram adicionados exemplos para as disciplinas de jogos e TCC, além de melhorada sua descrição. Também foi modificada a sigla de Jogos Digitais, de JoDI para Jogos, pois é o que as pessoas mais usam.

2019-04-06 01:22 UTC, pedroespindula commented
Oi, @RaylaMedeiros, muito obrigado por sua contribuição!!!!

2019-04-06 01:37 UTC, pedroespindula requested changes

2019-04-06 01:37 UTC, pedroespindula commented on src/lib/disciplinas.json
> +            "meaning": "Laboratório de Estrutura de Dados é uma disciplina obrigatória do 3º período do curso da Ciência de Computação que é paga em conjunto com EDA para o aprofundamento prático dos
Acredito que o correto seria `de` mesmo, pois essa preposição se refere a palavra `curso` e não a palavra `ciência`

2019-04-06 01:37 UTC, pedroespindula commented on src/lib/disciplinas.json
> +            "meaning": "Trabalho de Conclusão de Curso, é um trabalho obrigatório para concluir o curso de Ciência da Computação.",
Poderia ser adicionado uma descrição maior para o TCC? Explicar como é que ele funciona, o tipo de documento que é escrito, ou seja, dar mais alguns detalhes sobre o que ele é.

2019-04-06 01:37 UTC, pedroespindula commented on src/lib/disciplinas.json
> +            "meaning": "Jogos Digitais é uma cadeira optativa específica do curso de Ciência da Computação.",
Poderia ser adicionado uma explicação maior do que é visto na cadeira (ver definição de `AS` para ideias).

2019-04-06 01:38 UTC, thayannevls commented
Oi @RaylaMedeiros , muito obrigada pela contribuição! ❤️

2019-04-06 01:51 UTC, thayannevls commented on src/lib/disciplinas.json
> +            "meaning": "Trabalho de Conclusão de Curso, é um trabalho obrigatório para concluir o curso de Ciência da Computação.",
Sugestão:
```suggestion
            "meaning": "Trabalho de Conclusão de Curso, é um trabalho acadêmico obrigatório de muitos cursos de graduação que tem como função ser o instrumento de avaliação final de um curso superior.",
```

2019-04-06 01:56 UTC, pedroespindula commented on src/lib/disciplinas.json
> +            "meaning": "Laboratório de Estrutura de Dados é uma disciplina obrigatória do 3º período do curso da Ciência de Computação que é paga em conjunto com EDA para o aprofundamento prático dos
```suggestion
            "meaning": "Laboratório de Estrutura de Dados é uma disciplina obrigatória do 3º período do curso de Ciência da Computação que é paga em conjunto com EDA para o aprofundamento prático dos assuntos vistos em EDA.",
```

2019-04-06 02:13 UTC, thayannevls approved these changes
Obrigadaaaaa ❤️ 

Depois que ajeitar o que @pedroespindula sugeriu, por mim tá aceito!

2019-04-07 23:47 UTC, pedroespindula approved these changes

2019-04-07 23:47 UTC, merged